/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mc_system.gestao_igreja.ebd;

import com.mc_system.gestao_igreja.financeiro.mascara.MascaraValor;
import com.mc_system.gestao_igreja.utilitarios.ConectaBanco;
import com.mc_system.gestao_igreja.utilitarios.InOut;
import java.awt.FileDialog;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author marcos.junior
 */
public class LancaOferta extends javax.swing.JFrame {
MascaraValor valor1 = new MascaraValor();
ConectaBanco con;
ResultSet lRes;
FileDialog fbSalvar;
DecimalFormat  df = new DecimalFormat();
    /**
     * Creates new form LancaOferta
     */
    public LancaOferta() {
        initComponents();
        this.setLocationRelativeTo(null);
        Valor.setDocument(valor1);
        Valor.setEnabled(false);
        LancaOferta.setEnabled(false);
        fbSalvar = new FileDialog(this, "Salvar Arquivo", FileDialog.SAVE);
        
        df.applyPattern("R$ #,##0.00");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Aula = new javax.swing.JComboBox();
        Trimestre = new javax.swing.JComboBox();
        Ano = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        LancaOferta = new javax.swing.JButton();
        Valor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabOferta = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Progresso = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Lançamento de Oferta");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));

        Aula.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione o domingo>", "DOMINGO1", "DOMINGO2", "DOMINGO3", "DOMINGO4", "DOMINGO5", "DOMINGO6", "DOMINGO7", "DOMINGO8", "DOMINGO9", "DOMINGO10", "DOMINGO11", "DOMINGO12" }));

        Trimestre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione o Trimestre>", "1 TRIMESTE", "2 TRIMESTRE", "3 TRIMESTRE", "4 TRIMESTRE" }));

        Ano.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione o Ano>", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Aula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Trimestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Aula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Trimestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição"));

        LancaOferta.setText("Lançar");
        LancaOferta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LancaOfertaMousePressed(evt);
            }
        });

        jLabel2.setText("Valor :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(LancaOferta)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(LancaOferta))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Movimento"));

        Grupo.add(jRadioButton1);
        jRadioButton1.setText("Entrada");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        Grupo.add(jRadioButton2);
        jRadioButton2.setText("Relatorio");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa de Movimento"));

        TabOferta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Domingo", "Trimestre", "Ano", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabOferta);
        TabOferta.getColumnModel().getColumn(0).setResizable(false);
        TabOferta.getColumnModel().getColumn(1).setResizable(false);
        TabOferta.getColumnModel().getColumn(2).setResizable(false);
        TabOferta.getColumnModel().getColumn(3).setResizable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButton2.setText("Fechar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        jButton3.setText("Salvar Arquivo");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });

        Progresso.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Progresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton3))
                    .addComponent(Progresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        Valor.setEnabled(true);
        LancaOferta.setEnabled(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        Valor.setEnabled(false);
        LancaOferta.setEnabled(false);
        populaTabela();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void LancaOfertaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LancaOfertaMousePressed
        // TODO add your handling code here:
        String sSql = new String();
        con = new ConectaBanco();
        sSql = "Insert into EBD_Oferta (domingo,trimestre,ano,valor) values('"
                +Aula.getSelectedItem()+"','"
                +Trimestre.getSelectedItem()+"','"
                +Ano.getSelectedItem()+"','"
                +Valor.getText()+"');"
                ;
        con.conecta();
        try {
            con.executa(sSql);
        } catch (SQLException ex) {
            Logger.getLogger(LancaOferta.class.getName()).log(Level.SEVERE, null, ex);
        }
        con.desconecta();
        LimpaCampos();
    }//GEN-LAST:event_LancaOfertaMousePressed

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        // TODO add your handling code here:
        SalvaArquivo();
    }//GEN-LAST:event_jButton3MousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LancaOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LancaOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LancaOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LancaOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LancaOferta().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Ano;
    private javax.swing.JComboBox Aula;
    private javax.swing.ButtonGroup Grupo;
    private javax.swing.JButton LancaOferta;
    private javax.swing.JProgressBar Progresso;
    private javax.swing.JTable TabOferta;
    private javax.swing.JComboBox Trimestre;
    private javax.swing.JTextField Valor;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void populaTabela() {
        DefaultTableModel modelo1 = (DefaultTableModel) TabOferta.getModel();
      String sSql = new String();     
      int linha=0;
  
      con=new ConectaBanco();
       
       sSql="SELECT * from EBD_Oferta order by domingo,trimestre,ano;";
        con.conecta();
        try {
            con.executaSelect(sSql);
        } catch (SQLException ex) {
            Logger.getLogger(LancaOferta.class.getName()).log(Level.SEVERE, null, ex);
        }
        lRes=con.resultset; 
        System.out.println(lRes);
        System.out.println(sSql);
        try {                   
            modelo1.setRowCount(0);
            while (lRes.next()) {
                modelo1.addRow(new Object[]{
                            lRes.getString("domingo"),
                            lRes.getString("trimestre"),
                            lRes.getString("ano"),
                            lRes.getString("valor"),
                           });
            }
            TabOferta.setModel(modelo1);
        } catch (SQLException ex) {
            Logger.getLogger(LancaOferta.class.getName()).log(Level.SEVERE, null, ex);
        }
     con.desconecta();        
        
        
        
    }

    private void SalvaArquivo() {
         String nome_do_arquivo,sSql,contador;
          int i=0;
          int recebeProgresso=0;
          String domingo,trimestre,ano,valor12,valorfinal;
          con = new ConectaBanco();
        fbSalvar.setVisible(true);
        if (fbSalvar.getFile()==null) return;
        nome_do_arquivo = fbSalvar.getDirectory()+fbSalvar.getFile();
        PrintWriter out = null;
        try {       
            out = new PrintWriter(nome_do_arquivo+".csv");// **** FORMA MAIS RAPIDO DE SALVAR UM ARQUIVO EM .CSV*****
            
           sSql="SELECT * from EBD_Oferta order by domingo,trimestre,ano;";
            contador="SELECT Count(*) as contador from EBD_Oferta";
        con.conecta();
            try {
                con.executaSelect(contador);
            } catch (SQLException ex) {
                Logger.getLogger(LancaOferta.class.getName()).log(Level.SEVERE, null, ex);
            }
        //System.out.println("aqui é o contador"+contador);
        lRes=con.resultset;        
      // System.out.println(lRes);
       //System.out.println(contador);
        try {
            while (lRes.next()){
                   recebeProgresso=Integer.parseInt( lRes.getString("contador"));
            }
            } catch (SQLException ex) {
            InOut.MsgDeErro(null, contador);
        }
         // System.out.println(lRes);
        System.out.println("***********"+recebeProgresso);
        Progresso.setMaximum(recebeProgresso);
        Progresso.setMinimum(0); 
    
         
         if(!con.conecta())
        {
            InOut.MsgDeErro(null,"Erro ao conectar");
            return;            
        }
            try {
                con.executaSelect(sSql);
            } catch (SQLException ex) {
                Logger.getLogger(LancaOferta.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        lRes=con.resultset;        
        System.out.println(lRes);
        System.out.println(sSql);
        try 
        {   
            out.println(" ******* RELATORIO DE OFERTAS ESCOLA BLIBLICA DOMINICAL ********");
            out.println(";");
            out.println("DOMINGO;TRIMESTRE;ANO;VALOR;");
            while (lRes.next())
            {
                            domingo=lRes.getString("domingo");
                            trimestre=lRes.getString("trimestre");
                             ano=lRes.getString("ano");
                            valor12=lRes.getString("valor");
                           
                 out.println(domingo+";"+trimestre+";"+ano+";R$ "+valor12+";");
                 
     
                 try {
                        Thread.sleep(50);
                    } catch (InterruptedException e) {
                    }
                    i++;
                    Progresso.setValue(i); 
                 
            }            
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(LancaOferta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        con.desconecta();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(LancaOferta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            out.close();    
    InOut.MsgDeInformacao(null, "Arquivo Salvo!");
    }

    private void LimpaCampos() {
        Valor.setText(" ");
        populaTabela();
    }
}
