/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mc_system.gestao_igreja.ebd;

import com.mc_system.gestao_igreja.utilitarios.ConectaBanco;
import com.mc_system.gestao_igreja.utilitarios.InOut;
import com.mc_system.gestao_igreja.utilitarios.PrintUIWindow;
import java.awt.FileDialog;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;


/**
 *
 * @author marcos.junior
 */
public class Relatorio_Presenca extends javax.swing.JFrame {
FileDialog fbSalvar;
ConectaBanco con; 
ResultSet lRes;
    /**
     * Creates new form Relatorio_Presenca
     */
    public Relatorio_Presenca() {
        super("Relatório de Presença");
        initComponents();
        this.setLocationRelativeTo(null);
        
        faltaCriança.setText("      ");
        faltaJunior.setText("      ");
        faltaAdolescente.setText("      ");
        faltaJovem.setText("      " );
        faltaAdulto.setText("      ");
        faltaDiscipulado.setText("      ");
        
        presCrianca.setText("      ");
        presJunior.setText("      ");
        presAdolescente.setText("      ");
        presJovem.setText("      ");
        presAdulto.setText("      ");
        presDiscipulado.setText("      ");
        
        total1.setText("      ");
        total2.setText("      ");
        total3.setText("      ");
        total4.setText("      ");
        total5.setText("      ");
        total6.setText("      ");
        
        RelAula.setVisible(false);
        RelTrimestre.setVisible(false);
        fbSalvar = new FileDialog(this, "Salvar Arquivo", FileDialog.SAVE);
       // Anual.setVisible(false);
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        SalvaArquivo = new javax.swing.JFileChooser();
        jPanel11 = new javax.swing.JPanel();
        RelAno = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Aula = new javax.swing.JRadioButton();
        Trimestral = new javax.swing.JRadioButton();
        RelAula = new javax.swing.JComboBox();
        RelTrimestre = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        faltaAdolescente = new javax.swing.JLabel();
        faltaJunior = new javax.swing.JLabel();
        faltaCriança = new javax.swing.JLabel();
        faltaJovem = new javax.swing.JLabel();
        faltaAdulto = new javax.swing.JLabel();
        faltaDiscipulado = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        presCrianca = new javax.swing.JLabel();
        presJovem = new javax.swing.JLabel();
        presAdulto = new javax.swing.JLabel();
        presJunior = new javax.swing.JLabel();
        presDiscipulado = new javax.swing.JLabel();
        presAdolescente = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        total1 = new javax.swing.JLabel();
        matriculados = new javax.swing.JLabel();
        total2 = new javax.swing.JLabel();
        total3 = new javax.swing.JLabel();
        total4 = new javax.swing.JLabel();
        total5 = new javax.swing.JLabel();
        total6 = new javax.swing.JLabel();
        matriculados1 = new javax.swing.JLabel();
        matriculados2 = new javax.swing.JLabel();
        matriculados3 = new javax.swing.JLabel();
        matriculados4 = new javax.swing.JLabel();
        matriculados5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        RelAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione o Ano>", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099" }));

        jPanel3.setBackground(new java.awt.Color(240, 240, 240));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setForeground(new java.awt.Color(204, 255, 255));

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel2.setText("Tipo do Relatório");

        Aula.setBackground(new java.awt.Color(240, 240, 240));
        buttonGroup1.add(Aula);
        Aula.setText("Por Aula");
        Aula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AulaActionPerformed(evt);
            }
        });

        Trimestral.setBackground(new java.awt.Color(240, 240, 240));
        buttonGroup1.add(Trimestral);
        Trimestral.setText("Trimestral");
        Trimestral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrimestralActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Aula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Trimestral)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(69, 69, 69))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aula)
                    .addComponent(Trimestral))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        RelAula.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione o domingo>", "DOMINGO1", "DOMINGO2", "DOMINGO3", "DOMINGO4", "DOMINGO5", "DOMINGO6", "DOMINGO7", "DOMINGO8", "DOMINGO9", "DOMINGO10", "DOMINGO11", "DOMINGO12" }));

        RelTrimestre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione o Trimestre>", "1 TRIMESTE", "2 TRIMESTRE", "3 TRIMESTRE", "4 TRIMESTRE" }));

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 11)); // NOI18N
        jLabel3.setText("Crianças :");

        jLabel4.setFont(new java.awt.Font("Georgia", 3, 11)); // NOI18N
        jLabel4.setText("Juniores :");

        jLabel5.setFont(new java.awt.Font("Georgia", 3, 11)); // NOI18N
        jLabel5.setText("Adolescentes :");

        jLabel6.setFont(new java.awt.Font("Georgia", 3, 11)); // NOI18N
        jLabel6.setText("Jovens:");

        jLabel7.setFont(new java.awt.Font("Georgia", 3, 11)); // NOI18N
        jLabel7.setText("Adultos :");

        jLabel8.setFont(new java.awt.Font("Georgia", 3, 11)); // NOI18N
        jLabel8.setText("Discipulado :");

        faltaAdolescente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        faltaAdolescente.setForeground(new java.awt.Color(204, 0, 0));
        faltaAdolescente.setText("faltas");

        faltaJunior.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        faltaJunior.setForeground(new java.awt.Color(204, 0, 0));
        faltaJunior.setText("faltas");

        faltaCriança.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        faltaCriança.setForeground(new java.awt.Color(204, 0, 0));
        faltaCriança.setText("faltas");

        faltaJovem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        faltaJovem.setForeground(new java.awt.Color(204, 0, 0));
        faltaJovem.setText("faltas");

        faltaAdulto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        faltaAdulto.setForeground(new java.awt.Color(204, 0, 0));
        faltaAdulto.setText("faltas");

        faltaDiscipulado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        faltaDiscipulado.setForeground(new java.awt.Color(204, 0, 0));
        faltaDiscipulado.setText("faltas");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("faltas");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("faltas");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("faltas");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("faltas");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("faltas");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("faltas");

        presCrianca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        presCrianca.setForeground(new java.awt.Color(0, 0, 153));
        presCrianca.setText("pres");

        presJovem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        presJovem.setForeground(new java.awt.Color(0, 0, 153));
        presJovem.setText("pres");

        presAdulto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        presAdulto.setForeground(new java.awt.Color(0, 0, 153));
        presAdulto.setText("pres");

        presJunior.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        presJunior.setForeground(new java.awt.Color(0, 0, 153));
        presJunior.setText("pres");

        presDiscipulado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        presDiscipulado.setForeground(new java.awt.Color(0, 0, 153));
        presDiscipulado.setText("pres");

        presAdolescente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        presAdolescente.setForeground(new java.awt.Color(0, 0, 153));
        presAdolescente.setText("pres");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("presenças");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("presenças");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("presenças");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("presenças");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setText("presenças");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setText("presenças");

        total1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        total1.setText("total");

        matriculados.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        matriculados.setText("matriculados");

        total2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        total2.setText("total");

        total3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        total3.setText("total");

        total4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        total4.setText("total");

        total5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        total5.setText("total");

        total6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        total6.setText("total");

        matriculados1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        matriculados1.setText("matriculados");

        matriculados2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        matriculados2.setText("matriculados");

        matriculados3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        matriculados3.setText("matriculados");

        matriculados4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        matriculados4.setText("matriculados");

        matriculados5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        matriculados5.setText("matriculados");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(RelAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(RelAula, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RelTrimestre, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(64, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(faltaDiscipulado)
                            .addComponent(faltaAdulto)
                            .addComponent(faltaJovem)
                            .addComponent(faltaCriança)
                            .addComponent(faltaJunior)
                            .addComponent(faltaAdolescente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(presDiscipulado)
                            .addComponent(presAdulto)
                            .addComponent(presJovem)
                            .addComponent(presCrianca)
                            .addComponent(presJunior)
                            .addComponent(presAdolescente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(total1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matriculados))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(total2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matriculados1))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(total3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matriculados2))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(total4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matriculados3))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(total5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matriculados4))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(total6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matriculados5)))
                        .addGap(25, 25, 25))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RelAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RelAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RelTrimestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel11Layout.createSequentialGroup()
                                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(faltaCriança))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(faltaJunior))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(faltaAdolescente))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(faltaJovem))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(faltaAdulto))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(faltaDiscipulado)))
                                .addGroup(jPanel11Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel18))
                                .addGroup(jPanel11Layout.createSequentialGroup()
                                    .addComponent(presCrianca)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(presJunior)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(presAdolescente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(presJovem)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(presAdulto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(presDiscipulado)))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel30))))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(total2)
                                    .addComponent(matriculados1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(total3)
                                    .addComponent(matriculados2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(total4)
                                    .addComponent(matriculados3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(total5)
                                    .addComponent(matriculados4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(total6)
                                    .addComponent(matriculados5)))
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(total1)
                                .addComponent(matriculados)))))
                .addGap(33, 33, 33))
        );

        jButton1.setText("Salvar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jButton2.setText("Imprimir Tela");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        jButton3.setText("Fechar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });

        jButton4.setText("Iniciar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jButton3)
                        .addComponent(jButton4))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AulaActionPerformed
        // TODO add your handling code here:
        RelAula.setVisible(true);
        RelTrimestre.setVisible(true);
    }//GEN-LAST:event_AulaActionPerformed

    private void TrimestralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrimestralActionPerformed
        // TODO add your handling code here:
        RelAula.setVisible(false);
        RelTrimestre.setVisible(true);
    }//GEN-LAST:event_TrimestralActionPerformed

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3MousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        try {
            // TODO add your handling code here:
            SalvarArquivoCSV();
        } catch (IOException ex) {
            Logger.getLogger(Relatorio_Presenca.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // **********IMPRIME A TELA DE RELATORIO************
        jButton2.addActionListener(new PrintUIWindow(this));
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MousePressed
        // *****Inicia o Relatório *******
  if(Aula.isSelected()){
            try {
                MostrarRelatorioPresenca();
            } catch (SQLException ex) {
                Logger.getLogger(Relatorio_Presenca.class.getName()).log(Level.SEVERE, null, ex);
            }
  }else if(Trimestral.isSelected()){
            try {
                MostrarRelatorioPresenca();
           //  MostrarRelatorioPresenca();
             //  MostrarRelatorioPresenca();
            } catch (SQLException ex) {
                Logger.getLogger(Relatorio_Presenca.class.getName()).log(Level.SEVERE, null, ex);
            }
  }else{
      InOut.MsgDeAviso(null, "Escolha uma das opções de relatorio!");
  }
    }//GEN-LAST:event_jButton4MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio_Presenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio_Presenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio_Presenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio_Presenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorio_Presenca().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Aula;
    private javax.swing.JComboBox RelAno;
    private javax.swing.JComboBox RelAula;
    private javax.swing.JComboBox RelTrimestre;
    private javax.swing.JFileChooser SalvaArquivo;
    private javax.swing.JRadioButton Trimestral;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel faltaAdolescente;
    private javax.swing.JLabel faltaAdulto;
    private javax.swing.JLabel faltaCriança;
    private javax.swing.JLabel faltaDiscipulado;
    private javax.swing.JLabel faltaJovem;
    private javax.swing.JLabel faltaJunior;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel matriculados;
    private javax.swing.JLabel matriculados1;
    private javax.swing.JLabel matriculados2;
    private javax.swing.JLabel matriculados3;
    private javax.swing.JLabel matriculados4;
    private javax.swing.JLabel matriculados5;
    private javax.swing.JLabel presAdolescente;
    private javax.swing.JLabel presAdulto;
    private javax.swing.JLabel presCrianca;
    private javax.swing.JLabel presDiscipulado;
    private javax.swing.JLabel presJovem;
    private javax.swing.JLabel presJunior;
    private javax.swing.JLabel total1;
    private javax.swing.JLabel total2;
    private javax.swing.JLabel total3;
    private javax.swing.JLabel total4;
    private javax.swing.JLabel total5;
    private javax.swing.JLabel total6;
    // End of variables declaration//GEN-END:variables

    private void SalvarArquivoCSV() throws IOException {
       
         String nome_do_arquivo;
        fbSalvar.setVisible(true);
        if (fbSalvar.getFile()==null) return;
        nome_do_arquivo = fbSalvar.getDirectory()+fbSalvar.getFile();
        PrintWriter out = null;
            try {
                
                out = new PrintWriter(nome_do_arquivo+".csv");// **** FORMA MAIS RAPIDO DE SALVAR UM ARQUIVO EM .CSV*****
           
        out.println("*******RELATORIO DA ESCOLA BIBLICA DOMINICAL*******;");
        out.println("CLASSE;FALTAS;PRESENTES;TOTAL DE MATRICULADOS;");
        out.println("CRIANCAS;"+faltaCriança.getText()+";"+presCrianca.getText()+";"+total1.getText()+";");
        out.println("JUNIORES;"+faltaJunior.getText()+";"+presJunior.getText()+";"+total2.getText()+";");
        out.println("ADOLESCENTES;"+faltaAdolescente.getText()+";"+presAdolescente.getText()+";"+total3.getText()+";");
        out.println("JOVENS;"+faltaJovem.getText()+";"+presJovem.getText()+";"+total4.getText()+";");
        out.println("ADULTOS;"+faltaAdulto.getText()+";"+presAdulto.getText()+";"+total5.getText()+";");
        out.println("DISCIPULADO;"+faltaDiscipulado.getText()+";"+presDiscipulado.getText()+";"+total6.getText()+";");
//************ MOSTRA A BARRA DE PROGRESSO EM ANDAMENTO *****************        
        for (int i = 0; i < 100; i++) {
                    try {
                        Thread.sleep(5);
                    } catch (InterruptedException e) {
                    }
                    jProgressBar1.setValue(i);
                    System.out.println(i);
                } 
        
        out.close();
        InOut.MsgDeInformacao(null,"Arquivo salvo com sucesso!!");
       jProgressBar1.setValue(0);
       } catch (IOException ex) {
                Logger.getLogger(Relatorio_Presenca.class.getName()).log(Level.SEVERE, null, ex);
            }
   
}
//************Relatório anual de presenças e faltas ******************    
    private void MostrarRelatorioPresenca() throws SQLException {
    con=new ConectaBanco();
        String sSql = null,contador=new String();
        String classeAluno,presencaAluno = new String();
        int i = 2,recebeProgresso = 0;
        double pCrianca=0.0d;
        double fCrianca=0.0d;
        double pJunior=0.0d;
        double fJunior=0.0d;
        double pAdolescente=0.0d;
        double fAdolescente=0.0d;
        double pJovem=0.0d;
        double fJovem=0.0d;
        double pAdulto=0.0d;
        double fAdulto=0.0d;
        double pDiscipulado=0.0d;
        double fDiscipulado=0.0d;
        double tCrianca=0.0d;
        double tJunior=0.0d;
        double tAdolescente=0.0d;
        double tJovem=0.0d;
        double tAdulto=0.0d;
        double tDiscipulado=0.0d;
        
         pCrianca=0;
         fCrianca=0;
         pJunior=0;
         fJunior=0;
         pAdolescente=0;
         fAdolescente=0;
         pJovem=0;
         fJovem=0;
         pAdulto=0;
         fAdulto=0;
         pDiscipulado=0;
         fDiscipulado=0;
         tCrianca=0;
         tJunior=0;
         tAdolescente=0;
         tJovem=0;
         tAdulto=0;
         tDiscipulado=0;
         
         
         
          if(Trimestral.isSelected()){
             sSql="SELECT DOMINGO,TRIMESTRE,ANO,CLASSE_ALUNO,PRESENCA FROM EBD_PRESENCA WHERE ANO='"+RelAno.getSelectedItem()+"'AND TRIMESTRE='"+RelTrimestre.getSelectedItem()+"';";   
             contador="Select DOMINGO,TRIMESTRE,Ano, Count(*) as contador from ebd_presenca where ano='"+RelAno.getSelectedItem()+"'AND TRIMESTRE='"+RelTrimestre.getSelectedItem()+"';";
         }else if(Aula.isSelected()){
             sSql="SELECT DOMINGO,TRIMESTRE,ANO,CLASSE_ALUNO,PRESENCA FROM EBD_PRESENCA WHERE ANO='"+RelAno.getSelectedItem()+"'AND TRIMESTRE='"+RelTrimestre.getSelectedItem()+"'AND DOMINGO='"+RelAula.getSelectedItem()+"';";   
             contador="Select DOMINGO,TRIMESTRE,Ano, Count(*) as contador from ebd_presenca where ano='"+RelAno.getSelectedItem()+"'AND TRIMESTRE='"+RelTrimestre.getSelectedItem()+"'AND DOMINGO='"+RelAula.getSelectedItem()+"';";
         }else{
             InOut.MsgDeErro(null, contador+"\n erro");
         }
             
             
         con.conecta();
         if(!con.conecta())
        {
            InOut.MsgDeErro(null,"Erro ao conectar");
            return;            
        }
//********************** Inicia o contador para barra de progresso *********************
        con.executaSelect(contador);       
        lRes=con.resultset;        
      // System.out.println(lRes);
       //System.out.println(contador);
        try {
            while (lRes.next()){
                   recebeProgresso=Integer.parseInt( lRes.getString("contador"));
            }
            } catch (SQLException ex) {
            InOut.MsgDeErro(null, contador);
        }
         // System.out.println(lRes);
        System.out.println(recebeProgresso);
        jProgressBar1.setMaximum(recebeProgresso);
        jProgressBar1.setMinimum(0); 
//********************Inicia o processo de pesquisa **********************
        con.executaSelect(sSql); 
        System.out.println(sSql);
        lRes=con.resultset;    
        try 
        {           
            while (lRes.next())
            {
                 lRes.getString("DOMINGO");
                 lRes.getString("TRIMESTRE");
                 lRes.getString("ANO");
                 classeAluno=lRes.getString("CLASSE_ALUNO"); 
                 presencaAluno=lRes.getString("PRESENCA");
                 //----Fechamento----
                 if("CRIANCAS".equals(classeAluno)){
                     tCrianca=tCrianca + 1;
                     if("P".equals(presencaAluno)){
                         pCrianca = pCrianca + 1;
                     }else if("F".equals(presencaAluno)){
                         fCrianca = fCrianca + 1;
                     }
                 }else if("JUNIORES".equals(classeAluno)){
                     tJunior = tJunior + 1;
                     if("P".equals(presencaAluno)){
                         pJunior=pJunior + 1;
                     }else if("F".equals(presencaAluno)){
                         fJunior = fJunior + 1;
                     }
                 }else if("ADOLESCENTES".equals(classeAluno)){
                     tAdolescente = tAdolescente + 1;
                     if("P".equals(presencaAluno)){
                         pAdolescente=pAdolescente + 1;
                     }else if("F".equals(presencaAluno)){
                         fAdolescente = fAdolescente + 1;
                     }
                 }else if("JOVENS".equals(classeAluno)){
                     tJovem = tJovem + 1 ;
                     if("P".equals(presencaAluno)){
                         pJovem=pJovem + 1;
                     }else if("F".equals(presencaAluno)){
                         fJovem = fJovem + 1;
                     }
                 }else if("ADULTOS".equals(classeAluno)){
                     tAdulto = tAdulto+1;
                     if( "P".equals(presencaAluno)){
                         pAdulto=pAdulto + 1;
                     }else if("F".equals(presencaAluno)){
                         fAdulto = fAdulto + 1;
                     }
                 }else if("DISCIPULADO".equals(classeAluno)){
                     tDiscipulado=tDiscipulado+1;
                     if("P".equals(presencaAluno)){
                         pDiscipulado=pDiscipulado + 1;
                     }else if("F".equals(presencaAluno)){
                         fDiscipulado = fDiscipulado + 1;
                     }
                 
                 }      
            try {//Barra de progresso
                        Thread.sleep(5);
                    } catch (InterruptedException e) {
                    }
                    i++;
                    jProgressBar1.setValue(i);
                    System.out.println(i);  
                                              
            }            
            InOut.MsgDeAviso(null, "Fechamento de presença realizada com sucesso!");
            jProgressBar1.setValue(0);    
        }
        catch (SQLException ex) 
        {
            Logger.getLogger(Relatorio_Presenca.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        con.desconecta();
//********** ESCREVE O RELATORIO NA TELA*****************   
        
        faltaCriança.setText(String.valueOf(fCrianca));
        faltaJunior.setText(String.valueOf(fJunior));
        faltaAdolescente.setText(String.valueOf(fAdolescente));
        faltaJovem.setText(String.valueOf(fJovem) );
        faltaAdulto.setText(String.valueOf(fAdulto));
        faltaDiscipulado.setText(String.valueOf(fDiscipulado));
        
        presCrianca.setText(String.valueOf(pCrianca));
        presJunior.setText(String.valueOf(pJunior));
        presAdolescente.setText(String.valueOf(pAdolescente));
        presJovem.setText(String.valueOf(pJovem));
        presAdulto.setText(String.valueOf(pAdulto));
        presDiscipulado.setText(String.valueOf(pDiscipulado));
        
        total1.setText(String.valueOf(tCrianca));
        total2.setText(String.valueOf(tJunior));
        total3.setText(String.valueOf(tAdolescente));
        total4.setText(String.valueOf(tJovem));
        total5.setText(String.valueOf(tAdulto));
        total6.setText(String.valueOf(tDiscipulado)); 
        
        
        
    }

    
        
}  
    

