/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mc_system.gestao_igreja.financeiro.tesouraria_igreja;

import com.mc_system.gestao_igreja.utilitarios.InOut;
import com.mc_system.gestao_igreja.utilitarios.Configuracao_PC;
import com.mc_system.gestao_igreja.utilitarios.ConectaBanco;
import com.mc_system.gestao_igreja.utilitarios.FormataData;
import com.mc_system.gestao_igreja.utilitarios.Parametros;
import com.mc_system.gestao_igreja.financeiro.mascara.MascaraData;
import com.mc_system.gestao_igreja.financeiro.mascara.MascaraValor;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;


/**
 *
 * @author marcos.junior
 */
public class Principal extends javax.swing.JFrame {

    public String usuario = Parametros.getsNmUsuas();
    MascaraData dataLancamento = new MascaraData();
    MascaraValor valorLancamento = new MascaraValor();
    ConectaBanco con;
    ResultSet lRes;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        /*try {
            MaskFormatter data = new MaskFormatter("##/##/####");
            data.install(txData);
        } catch (ParseException ex) {
            InOut.MsgDeErro(null, ex.getMessage());
        }
       */ 
        txData.setDocument(dataLancamento);
        txValor.setDocument(valorLancamento);
        
        txDataLog.setText(Configuracao_PC.MostraDataPC());
        txUsuario.setText(usuario);
        
        DesativaPainel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbDizimo = new javax.swing.JRadioButton();
        rbSaida = new javax.swing.JRadioButton();
        rbOferta = new javax.swing.JRadioButton();
        rbOfertaEBD = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txValor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txMembro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txPesquisaMembro = new javax.swing.JTextField();
        btPesquisaMembro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMembros = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txDescricao = new javax.swing.JTextArea();
        btSalvar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        txData = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txUsuario = new javax.swing.JLabel();
        txDataLog = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestão Igreja - Financeiro");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Lançamento"));

        buttonGroup1.add(rbDizimo);
        rbDizimo.setText("Entrada - Dízimo");
        rbDizimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDizimoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbSaida);
        rbSaida.setText("Saída");
        rbSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSaidaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbOferta);
        rbOferta.setText("Entrada - Oferta");
        rbOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOfertaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbOfertaEBD);
        rbOfertaEBD.setText("Entrada - Oferta EBD");
        rbOfertaEBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOfertaEBDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbDizimo)
                    .addComponent(rbSaida)
                    .addComponent(rbOferta)
                    .addComponent(rbOfertaEBD))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbDizimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbOferta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbOfertaEBD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbSaida)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lançamento"));

        jLabel1.setText("Data :");

        jLabel2.setText("Valor :");

        jLabel3.setText("Membro:");

        jLabel4.setText("Descrição:");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa de Membro"));

        btPesquisaMembro.setText("Pesquisar");
        btPesquisaMembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaMembroActionPerformed(evt);
            }
        });

        tbMembros.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tbMembros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbMembros.getTableHeader().setReorderingAllowed(false);
        tbMembros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMembrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMembros);
        tbMembros.getColumnModel().getColumn(0).setResizable(false);
        tbMembros.getColumnModel().getColumn(0).setPreferredWidth(10);
        tbMembros.getColumnModel().getColumn(1).setResizable(false);
        tbMembros.getColumnModel().getColumn(1).setPreferredWidth(250);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txPesquisaMembro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPesquisaMembro))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txPesquisaMembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisaMembro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addContainerGap())
        );

        txDescricao.setColumns(20);
        txDescricao.setRows(5);
        jScrollPane2.setViewportView(txDescricao);

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txValor, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(txData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(btSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txMembro)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btSalvar)
                    .addComponent(txData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txMembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Relatórios"));

        jButton5.setText("Lançamentos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Dízimos");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Sistema"));

        jLabel5.setText("Usuário:");

        jLabel6.setText("Data :");

        txUsuario.setText("jLabel7");

        txDataLog.setText("jLabel8");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txUsuario))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txDataLog)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txDataLog))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSaidaActionPerformed
        //desativa formularios
        txData.setEnabled(true);
        txDescricao.setEnabled(true);
        txMembro.setEnabled(false);
        txPesquisaMembro.setEnabled(false);
        txValor.setEnabled(true);

        //desativa botões
        btLimpar.setEnabled(true);
        btPesquisaMembro.setEnabled(false);
        btSalvar.setEnabled(true);

        tbMembros.setEnabled(false);
    }//GEN-LAST:event_rbSaidaActionPerformed

    private void tbMembrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMembrosMouseClicked
       SelecionaMembro();
    }//GEN-LAST:event_tbMembrosMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        TelaLancamentos abrir = new TelaLancamentos();
        abrir.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void rbDizimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDizimoActionPerformed
        //desativa formularios
        txData.setEnabled(true);
        txDescricao.setEnabled(false);
        txMembro.setEnabled(true);
        txPesquisaMembro.setEnabled(true);
        txValor.setEnabled(true);

        //desativa botões
        btLimpar.setEnabled(true);
        btPesquisaMembro.setEnabled(true);
        btSalvar.setEnabled(true);

        tbMembros.setEnabled(true);
    }//GEN-LAST:event_rbDizimoActionPerformed

    private void rbOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOfertaActionPerformed
        //desativa formularios
        txData.setEnabled(true);
        txDescricao.setEnabled(false);
        txMembro.setEnabled(false);
        txPesquisaMembro.setEnabled(false);
        txValor.setEnabled(true);

        //desativa botões
        btLimpar.setEnabled(true);
        btPesquisaMembro.setEnabled(false);
        btSalvar.setEnabled(true);

        tbMembros.setEnabled(false);
    }//GEN-LAST:event_rbOfertaActionPerformed

    private void rbOfertaEBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOfertaEBDActionPerformed
        //desativa formularios
        txData.setEnabled(true);
        txDescricao.setEnabled(false);
        txMembro.setEnabled(false);
        txPesquisaMembro.setEnabled(false);
        txValor.setEnabled(true);

        //desativa botões
        btLimpar.setEnabled(true);
        btPesquisaMembro.setEnabled(false);
        btSalvar.setEnabled(true);

        tbMembros.setEnabled(false);
    }//GEN-LAST:event_rbOfertaEBDActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Dizimos abrir = new Dizimos();
        abrir.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if(rbSaida.isSelected()&&txDescricao.getText().trim()==null){
            InOut.MsgDeErro(null, "Descreva a Saida de Caixa!");
        }else{
            SalvaLancamento();
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        LimpaCampos();
        DesativaPainel();
        txDataLog.setText(Configuracao_PC.MostraDataPC());
    }//GEN-LAST:event_btLimparActionPerformed

    private void btPesquisaMembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaMembroActionPerformed
        PesquisaMembro();
    }//GEN-LAST:event_btPesquisaMembroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            InOut.MsgDeErro(null, ex.getMessage());
        } catch (InstantiationException ex) {
            InOut.MsgDeErro(null, ex.getMessage());
        } catch (IllegalAccessException ex) {
            InOut.MsgDeErro(null, ex.getMessage());
        } catch (UnsupportedLookAndFeelException ex) {
            InOut.MsgDeErro(null, ex.getMessage());
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPesquisaMembro;
    private javax.swing.JButton btSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbDizimo;
    private javax.swing.JRadioButton rbOferta;
    private javax.swing.JRadioButton rbOfertaEBD;
    private javax.swing.JRadioButton rbSaida;
    private javax.swing.JTable tbMembros;
    private javax.swing.JFormattedTextField txData;
    private javax.swing.JLabel txDataLog;
    private javax.swing.JTextArea txDescricao;
    private javax.swing.JTextField txMembro;
    private javax.swing.JTextField txPesquisaMembro;
    private javax.swing.JLabel txUsuario;
    private javax.swing.JTextField txValor;
    // End of variables declaration//GEN-END:variables

    private void DesativaPainel() {
        //desativa formularios
        txData.setEnabled(false);
        txDescricao.setEnabled(false);
        txMembro.setEnabled(false);
        txPesquisaMembro.setEnabled(false);
        txValor.setEnabled(false);

        //desativa botões
        btLimpar.setEnabled(false);
        btPesquisaMembro.setEnabled(false);
        btSalvar.setEnabled(false);
        
        rbDizimo.setSelected(false);
        rbOferta.setSelected(false);
        rbOfertaEBD.setSelected(false);
        rbSaida.setSelected(false);
        
        tbMembros.setEnabled(false);
        
    }

    private void SalvaLancamento() {
        String sSql,sSql2;
        sSql = new String();
        boolean verifica;
        con = new ConectaBanco();
        
        
        if(rbDizimo.isSelected()){ 
            if(txMembro.getText().trim()==null){
                InOut.MsgDeErro(null, "Preencha o Campo Membro!");
            }
            else{
                sSql="insert into lancamento(data_lancamento,tipo_lancamento,descricao,valor,membro,usuario_sistema,data_log) values('"
                        + ""+FormataData.FormataDataBanco(txData.getText())+"','"
                        +"ENTRADA','DIZIMO','"
                        +txValor.getText()+"','"
                        +txMembro.getText()+"','"
                        +txUsuario.getText()+"','"
                        +FormataData.FormataDataBanco(txDataLog.getText())+"');"

                        ;
                verifica=VerificaCadastro(txMembro.getText(),FormataData.RetornaAno(txData.getText()));
                System.out.println("**** Verifica****"+verifica);
                if(verifica){
                    sSql2="INSERT INTO DIZIMO(NOME,"+FormataData.MostraMesExtenso(txData.getText()) +",ano) values ('"+txMembro.getText()+"','OK','"+FormataData.RetornaAno(txData.getText()) +"')";
                }else{
                    sSql2="update dizimo set "+FormataData.MostraMesExtenso(txData.getText())+" ='OK' where nome='"+txMembro.getText()+"' and ano='"+FormataData.RetornaAno(txData.getText())+"';";
                }
                 
                System.out.println(sSql2);
                con.conecta();
                try {
                    con.executa(sSql2);
                } catch (SQLException ex) {
                    InOut.MsgDeErro(null, ex.getMessage());
                }
                con.desconecta();
            }
        }else if(rbOferta.isSelected()){
            sSql="insert into lancamento(data_lancamento,tipo_lancamento,descricao,valor,usuario_sistema,data_log) values('"
                        + ""+FormataData.FormataDataBanco(txData.getText())+"','"
                        +"ENTRADA','OFERTA','"
                        +txValor.getText()+"','"
                        +txUsuario.getText()+"','"
                        +FormataData.FormataDataBanco(txDataLog.getText())+"');"
                        ;
        }else if(rbOfertaEBD.isSelected()){
            sSql="insert into lancamento(data_lancamento,tipo_lancamento,descricao,valor,usuario_sistema,data_log) values('"
                        + ""+FormataData.FormataDataBanco(txData.getText())+"','"
                        +"ENTRADA','OFERTA_EBD','"
                        +txValor.getText()+"','"
                        +txUsuario.getText()+"','"
                        +FormataData.FormataDataBanco(txDataLog.getText())+"');"
                        ;
        }else if(rbSaida.isSelected()){
            sSql="insert into lancamento(data_lancamento,tipo_lancamento,descricao,valor,usuario_sistema,data_log) values('"
                        + ""+FormataData.FormataDataBanco(txData.getText())+"','"
                        +"SAIDA','"
                        +txDescricao.getText()+"','"
                        +txValor.getText()+"','"
                        +txUsuario.getText()+"','"
                        +FormataData.FormataDataBanco(txDataLog.getText())+"');"
                        ;
        }
        con.conecta();
        try {
            con.executa(sSql);
            InOut.MsgDeInformacao(null, "Informações salvas com sucesso!");
        } catch (SQLException ex) {
            InOut.MsgDeErro(null, ex.getMessage());
        }
        con.desconecta();
                
    }

    private void LimpaCampos() {
        txData.setText(null);
        txDescricao.setText(null);
        txMembro.setText(null);
        txPesquisaMembro.setText(null);
        txValor.setText(null);
    }

    private void PesquisaMembro() {
        String sSql ;
        
        DefaultTableModel modelo1 = (DefaultTableModel) tbMembros.getModel();
        con=new ConectaBanco();
        
        sSql="SELECT idmembros,NOME FROM MEMBROS WHERE NOME LIKE'%"+txPesquisaMembro.getText()+ "%'ORDER BY NOME;";
        con.conecta();
        try {
            con.executaSelect(sSql);
            lRes=con.resultset;
            modelo1.setRowCount(0);
            while (lRes.next()) {
                modelo1.addRow(new Object[]{
                            lRes.getString("idMembros"),
                            lRes.getString("NOME")
                           });
            }
    
        } catch (SQLException ex) {
            InOut.MsgDeErro(null, ex.getMessage());
        }
        con.desconecta();
    }

    private void SelecionaMembro() {
        int linha;
        String sSql ;
        String sMembro ; 
        con = new ConectaBanco();
        
        linha=tbMembros.getSelectedRow();
        sMembro = tbMembros.getValueAt(linha, 0).toString();
        
        sSql="SELECT idmembros,NOME FROM MEMBROS WHERE idMembros='"+sMembro+"'";
        
        con.conecta();
        try {
            con.executaSelect(sSql);
            lRes = con.resultset;
            while(lRes.next()){
                txMembro.setText(lRes.getString("nome"));
            }
        } catch (SQLException ex) {
            InOut.MsgDeErro(null, ex.getMessage());
        }
        con.desconecta();
    }

    private boolean VerificaCadastro(String text, String RetornaAno) {
        
        String existe = new String();
        con = new ConectaBanco();
        
        con.conecta();
        try {
            con.executaSelect("Select nome,ano from dizimo where nome='"+text+"' and ano='"+RetornaAno+"';");
            lRes = con.resultset;
            while(lRes.next()){
                existe = lRes.getString("nome");
            }    
        } catch (SQLException ex) {
            InOut.MsgDeErro(null, ex.getMessage());
        }
        con.desconecta();
        System.out.println("*** verificação de membro***"+existe);
        if(existe==null){
            return true;
        }else{
            return false;
        }    
    }
    
}
