/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mc_system.gestao_igreja.financeiro.tesouraria_igreja;

import com.mc_system.gestao_igreja.financeiro.mascara.MascaraData;
import com.mc_system.gestao_igreja.utilitarios.ConectaBanco;
import com.mc_system.gestao_igreja.utilitarios.FormataData;
import com.mc_system.gestao_igreja.utilitarios.InOut;
import java.awt.FileDialog;
import java.awt.HeadlessException;
import java.awt.print.PrinterException;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marcos.junior
 */
public class TelaLancamentos extends javax.swing.JFrame {
MascaraData data1 = new MascaraData();
MascaraData data2 = new MascaraData();
MascaraData data3 = new MascaraData();
MascaraData data4 = new MascaraData();
String sSql;
ResultSet lRes;
ConectaBanco con;
FileDialog fdSalvar;
    /**
     * Creates new form TelaLancamentos
     */
    public TelaLancamentos() {
        initComponents();
        txDataFinal.setDocument(data1);
        txDataFinal1.setDocument(data3);
        txDataInicial.setDocument(data2);
        txDataInicial1.setDocument(data4);
       
        txDataFinal.setEnabled(false);
        txDataInicial.setEnabled(false);
        
        btPesquisar.setEnabled(false);
        
        this.setLocationRelativeTo(null);
        
        txEntradasPeriodo.setText(null);
        txSaidaPeriodo.setText(null);
        txSaldoGeral.setText(null);
        txSaldoPeriodo.setText(null);
    
        fdSalvar = new FileDialog(this, "Salvar");
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        rbDiario = new javax.swing.JRadioButton();
        rbPeriodo = new javax.swing.JRadioButton();
        rbTotal = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLancamento = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txDataInicial = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txDataFinal = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbLancamento1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txDataFinal1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txDataInicial1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txEntradasPeriodo = new javax.swing.JLabel();
        txSaidaPeriodo = new javax.swing.JLabel();
        txSaldoPeriodo = new javax.swing.JLabel();
        txSaldoGeral = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestão Igreja -Caixa");

        jDesktopPane1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Lançamento"));

        buttonGroup1.add(rbDiario);
        rbDiario.setText("Diário");
        rbDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDiarioActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbPeriodo);
        rbPeriodo.setText("Período");
        rbPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPeriodoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbTotal);
        rbTotal.setText("Total");
        rbTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbDiario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbPeriodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbTotal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDiario)
                    .addComponent(rbPeriodo)
                    .addComponent(rbTotal))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.setBounds(10, 10, 195, 69);
        jDesktopPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("   "));

        jButton2.setText("Imprimir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Salvar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jPanel3.setBounds(210, 10, 287, 69);
        jDesktopPane1.add(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));

        tbLancamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbLancamento);

        jLabel1.setText("Data :");

        jLabel2.setText("até");

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPesquisar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBounds(10, 90, 488, 303);
        jDesktopPane1.add(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Relatório de Lançamentos", jDesktopPane1);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Lançamentos"));

        tbLancamento1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Data", "Tipo de entrada", "Valor", "Descricao"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbLancamento1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbLancamento1);
        tbLancamento1.getColumnModel().getColumn(0).setResizable(false);
        tbLancamento1.getColumnModel().getColumn(0).setPreferredWidth(15);
        tbLancamento1.getColumnModel().getColumn(1).setResizable(false);
        tbLancamento1.getColumnModel().getColumn(1).setPreferredWidth(30);
        tbLancamento1.getColumnModel().getColumn(2).setResizable(false);
        tbLancamento1.getColumnModel().getColumn(2).setPreferredWidth(30);
        tbLancamento1.getColumnModel().getColumn(3).setResizable(false);
        tbLancamento1.getColumnModel().getColumn(3).setPreferredWidth(150);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Fechar Caixa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("até");

        jLabel3.setText("Data :");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Caixa"));

        jLabel5.setText("Total de Entradas no Período :");

        jLabel6.setText("Total de Saídas no Período :");

        jLabel7.setText("Saldo no Período:");

        jLabel8.setText("Saldo Geral :");

        txEntradasPeriodo.setText("jLabel9");

        txSaidaPeriodo.setText("jLabel10");

        txSaldoPeriodo.setText("jLabel11");

        txSaldoGeral.setText("jLabel12");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txSaidaPeriodo)
                            .addComponent(txEntradasPeriodo))
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txSaldoPeriodo)
                            .addComponent(txSaldoGeral))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txEntradasPeriodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txSaidaPeriodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txSaldoPeriodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txSaldoGeral))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txDataInicial1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txDataFinal1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txDataInicial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txDataFinal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Fechamento de Caixa", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        PesquisaLancamento();
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        fdSalvar.setVisible(true);
        if(fdSalvar.getFile()!=null){
           SalvarCSV(); 
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            tbLancamento.print(JTable.PrintMode.FIT_WIDTH, null, null, true, null, true);

        } catch (PrinterException ex) {
            Logger.getLogger(TelaLancamentos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (HeadlessException ex) {
            Logger.getLogger(TelaLancamentos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rbTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTotalActionPerformed
        txDataFinal.setEnabled(false);
        txDataInicial.setEnabled(false);
        btPesquisar.setEnabled(true);
    }//GEN-LAST:event_rbTotalActionPerformed

    private void rbPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPeriodoActionPerformed
        txDataFinal.setEnabled(true);
        txDataInicial.setEnabled(true);
        btPesquisar.setEnabled(true);
    }//GEN-LAST:event_rbPeriodoActionPerformed

    private void rbDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDiarioActionPerformed
        txDataFinal.setEnabled(false);
        txDataInicial.setEnabled(true);
        btPesquisar.setEnabled(true);
    }//GEN-LAST:event_rbDiarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FechamentoCaixa();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLancamentos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rbDiario;
    private javax.swing.JRadioButton rbPeriodo;
    private javax.swing.JRadioButton rbTotal;
    private javax.swing.JTable tbLancamento;
    private javax.swing.JTable tbLancamento1;
    private javax.swing.JTextField txDataFinal;
    private javax.swing.JTextField txDataFinal1;
    private javax.swing.JTextField txDataInicial;
    private javax.swing.JTextField txDataInicial1;
    private javax.swing.JLabel txEntradasPeriodo;
    private javax.swing.JLabel txSaidaPeriodo;
    private javax.swing.JLabel txSaldoGeral;
    private javax.swing.JLabel txSaldoPeriodo;
    // End of variables declaration//GEN-END:variables

    private void SalvarCSV() {
        
        con = new ConectaBanco();
        String[] lancamentos = null;
        
        if(rbDiario.isSelected()){
            sSql = "Select * lancamento where data_lancamento='"+FormataData.FormataDataBanco(txDataInicial.getText())+"' order by tipo_lancamento,idLancamento;";
        }else if(rbPeriodo.isSelected()){
            sSql = "Select * from registroponto where  dataLancamento between '"+FormataData.FormataDataBanco(txDataInicial.getText()) 
                +"' and '"+FormataData.FormataDataBanco(txDataFinal.getText())+"' order by tipo_lancamento,data_lancamento;";
        }else if(rbTotal.isSelected()){
            sSql = "Select * lancamento  order by tipo_lancamento,idLancamento;";
        }
        
        con.conecta();
        try {
            con.executaSelect(sSql);
            lRes = con.resultset;
            
            PrintWriter out = new PrintWriter(fdSalvar.getDirectory()+fdSalvar.getFile());
            while (lRes.next()){
                
                  lancamentos[0]= lRes.getString("data_lancamento")+";";
                  lancamentos[1]= lRes.getString("tipo_lancamento")+";";
                  lancamentos[2]= lRes.getString("valor")+";";
                  lancamentos[3]= lRes.getString("descricao")+";";
               out.print(lancamentos[0]+lancamentos[1]+lancamentos[2]+lancamentos[3]);
            }
            out.close();
        } catch (SQLException ex) {
            InOut.MsgDeErro(null, ex.getMessage());
        }catch (FileNotFoundException ex) {
                Logger.getLogger(TelaLancamentos.class.getName()).log(Level.SEVERE, null, ex);
       }
        con.desconecta();
    }

    private void PesquisaLancamento() {
        con = new ConectaBanco();
        DefaultTableModel modelo1 = (DefaultTableModel) tbLancamento.getModel();
        
        if(rbDiario.isSelected()){
            sSql = "Select * from lancamento where data_lancamento='"+FormataData.FormataDataBanco(txDataInicial.getText())+"' order by tipo_lancamento,idLancamento;";
        }else if(rbPeriodo.isSelected()){
            sSql = "Select * from lancamento where  data_lancamento between '"+FormataData.FormataDataBanco(txDataInicial.getText()) 
                +"' and '"+FormataData.FormataDataBanco(txDataFinal.getText())+"' order by tipo_lancamento,data_lancamento;";
        }else if(rbTotal.isSelected()){
            sSql = "Select * from lancamento  order by tipo_lancamento,idLancamento;";
        }
        
        con.conecta();
        try {
            con.executaSelect(sSql);
        } catch (SQLException ex) {
            InOut.MsgDeErro(null, ex.getMessage());
        }
        lRes = con.resultset;
        modelo1.setRowCount(0);
        try {
            while (lRes.next()){
                modelo1.addRow(new Object[]{
                   FormataData.FormataDataExibir( lRes.getString("data_lancamento")),
                                      lRes.getString("tipo_lancamento"),
                                      lRes.getString("valor").replace(".", ","),
                                      lRes.getString("descricao"),
               });
            }
            tbLancamento.setModel(modelo1);
        } catch (SQLException ex) {
            InOut.MsgDeErro(null, ex.getMessage());
        }
        con.desconecta();
        
    }

    private void FechamentoCaixa() {
        con = new ConectaBanco();
        sSql = new String();
        
        String verifica = new String();
        double entradames=0.0d;
        double saidames=0.0d;
        double saldofinalmes=0.0d;
        
        double entrada=0.0d;
        double saida=0.0d;
        double saldofinal=0.0d;
        
        double calcula=0.0d;
        double calcula2=0.0d;
        String datainicial,datafinal;
        
        entradames=0;
        saidames=0;
        saldofinalmes=0;
        
        entrada = 0;
        saida = 0;
        saldofinal = 0;
        
        calcula=0;
        calcula2=0;        
        
      //  sSql = "Select * from lancamento where  data_lancamento between '"+FormataData.FormataDataBanco(txDataInicial1.getText()) 
        //        +"' and '"+FormataData.FormataDataBanco(txDataFinal1.getText())+"' order by tipo_lancamento,data_lancamento;";
        
       sSql= "Select sum(valor)as valor,data_lancamento,tipo_lancamento,descricao from lancamento where  data_lancamento between '"+FormataData.FormataDataBanco(txDataInicial1.getText()) 
            +"' and '"+FormataData.FormataDataBanco(txDataFinal1.getText())+"' group by descricao,data_lancamento order by tipo_lancamento;";
        
        System.out.println(sSql);
        con.conecta();
        try {
//**********************************************************************************************************************

            con.executaSelect(sSql);
            lRes = con.resultset;
            while (lRes.next()){
                
                   
                   verifica=lRes.getString("tipo_lancamento");
                   switch(verifica){
                       case"ENTRADA":
                           calcula = Double.parseDouble(lRes.getString("valor").replace(',', '.'));
                           entradames = entradames + calcula;
                           break;
                       case"SAIDA":
                           calcula2 = Double.parseDouble(lRes.getString("valor").replace(',', '.'));
                           saidames = saidames + calcula2;
                           break;
                   }
                   saldofinalmes=  entradames - saidames;
            }
            
//**********************************************************************************************************************
            
            DefaultTableModel modelo1 = (DefaultTableModel) tbLancamento1.getModel();
            modelo1.setRowCount(0);
            con.executaSelect(sSql);
            lRes = con.resultset;
            while (lRes.next()){
                modelo1.addRow(new Object[]{
                   FormataData.FormataDataExibir( lRes.getString("data_lancamento")),
                                      lRes.getString("tipo_lancamento"),
                                      lRes.getString("valor").replace(".", ","),
                                      lRes.getString("descricao"),
               });
            }
            tbLancamento1.setModel(modelo1);
            
//**********************************************************************************************************************            
            
            con.executaSelect("Select * from lancamento  order by tipo_lancamento,idLancamento;");
            lRes = con.resultset;
            
            while (lRes.next()){
                
                   
                   verifica=lRes.getString("tipo_lancamento");
                   switch(verifica){
                       case"ENTRADA":
                           calcula = Double.parseDouble(lRes.getString("valor").replace(',', '.'));
                           entrada = entrada + calcula;
                           break;
                       case"SAIDA":
                           calcula2 = Double.parseDouble(lRes.getString("valor").replace(',', '.'));
                           saida = saida + calcula2;
                           break;
                   }
                   saldofinal=  entrada - saida;
            }
             
//**********************************************************************************************************************            
            
        } catch (SQLException ex) {
            InOut.MsgDeErro(null, ex.getMessage());
        }
        con.desconecta();
//**********************************************************************************************************************            
        DecimalFormat  df = new DecimalFormat();
        df.applyPattern("R$ #,##0.00");
        
        txEntradasPeriodo.setText(df.format(entradames));
        txSaidaPeriodo.setText(df.format(saidames));
        txSaldoPeriodo.setText(df.format(saldofinalmes));
        txSaldoGeral.setText(df.format(saldofinal));
        
        int Salvamento = InOut.MsgDeSimNao("Salvar Caixa", "Deseja Salvar o Relatório de Caixa?");
        if(Salvamento ==0){
            try {
                SalvaCaixa();
            } catch (FileNotFoundException ex) {
                InOut.MsgDeErro(null, ex.getMessage());
            }
        }
        
//**********************************************************************************************************************                    
    }
    
    private void SalvaCaixa() throws FileNotFoundException{
        String nome_do_arquivo,sSql,contador;
        int i=0;
        int recebeProgresso=0;
        String Data,Tipo,Valor,Descricao,Tipo1,Valor1;
        fdSalvar.setVisible(true);
        if (fdSalvar.getFile()==null) return;
        nome_do_arquivo = fdSalvar.getDirectory()+fdSalvar.getFile()+".csv";
        PrintWriter out = new PrintWriter(nome_do_arquivo);// **** FORMA MAIS RAPIDO DE SALVAR UM ARQUIVO EM .CSV*****
        out.println("*******RELATORIO FINANCEIRO -  PERIODO :"+txDataInicial1.getText()+" A "+txDataFinal1.getText()+"*******;");
        out.println("DATA;TIPO DE LANCAMENTO;VALOR;DESCRICAO;");
        
       sSql= "Select sum(valor)as valor,data_lancamento,tipo_lancamento,descricao from lancamento where  data_lancamento between '"+FormataData.FormataDataBanco(txDataInicial1.getText()) 
            +"' and '"+FormataData.FormataDataBanco(txDataFinal1.getText())+"' group by descricao,data_lancamento order by tipo_lancamento;";

        con.conecta();
        try {
            con.executaSelect(sSql);
            lRes = con.resultset;
            while(lRes.next()){
                Data = FormataData.FormataDataExibir(lRes.getString("data_lancamento"));
                Tipo = lRes.getString("tipo_lancamento");
                Valor = lRes.getString("valor").replace(".", ",");
                Descricao = lRes.getString("descricao");
                
                out.println(Data+";"+Tipo+";"+Valor+";"+Descricao+";");
            }
            sSql= "Select sum(valor)as valor,data_lancamento,tipo_lancamento,descricao from lancamento where  data_lancamento between '"+FormataData.FormataDataBanco(txDataInicial1.getText()) 
            +"' and '"+FormataData.FormataDataBanco(txDataFinal1.getText())+"' group by tipo_lancamento order by tipo_lancamento;";
                
            out.println(";");
            out.println(";");
            con.executaSelect(sSql);
            lRes = con.resultset;
            while(lRes.next()){
                Tipo1 = lRes.getString("tipo_lancamento");
                Valor1 = lRes.getString("valor").replace(".", ",");
                
                out.println(";"+Tipo1+";"+Valor1+";;");
            }
            
            
        } catch (SQLException ex) {
           InOut.MsgDeErro(null, ex.getMessage());
           return;
        }
        con.desconecta();
        out.close();
        InOut.MsgDeInformacao(null, "Arquivo salvo!");
    }
}
