/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mc_system.gestao_igreja_principal;


import com.mc_system.gestao_igreja.criaConexao.CriaUsuario;
import com.mc_system.gestao_igreja.ebd.*;
import com.mc_system.gestao_igreja.ebd.LancaOferta;
import com.mc_system.gestao_igreja.financeiro.tesouraria_igreja.*;
import com.mc_system.gestao_igreja.secretaria.Agenda;
import com.mc_system.gestao_igreja.secretaria.Secretaria;
import com.mc_system.gestao_igreja.utilitarios.*;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;



/**
 *
 * @author marcos.junior
 */
public class TelaPrincipal extends javax.swing.JFrame {
ConectaBanco con;
public String usuario = Parametros.getsNmUsuas();
public String senha = Parametros.getsSenhaUsuas();
public String funcao = Parametros.getsFuncao();
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        UsuarioSistema.setText("Usuário do Sistema : "+usuario);
        FuncaoUsuario.setText("Função : "+funcao);
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        con = new ConectaBanco();   
        VerificaUsuario();
        MostraDataAtual();
        MostraConexao();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        Cliente_IP = new javax.swing.JLabel();
        IP_servidor = new javax.swing.JLabel();
        MostrandoData = new javax.swing.JLabel();
        UsuarioSistema = new javax.swing.JLabel();
        FuncaoUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        SairButton = new javax.swing.JMenuItem();
        EBD_Menu = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        Financeiro_Menu = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        Secretaria_Menu = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        Agenda_Menu = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        tiMenu = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestão de Igrejas");
        setBackground(new java.awt.Color(0, 0, 204));
        setForeground(new java.awt.Color(51, 51, 255));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuração de Conexão"));

        Cliente_IP.setText("jLabel1");

        IP_servidor.setText("jLabel1");

        MostrandoData.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MostrandoData.setForeground(new java.awt.Color(0, 0, 204));
        MostrandoData.setText("jLabel1");
        MostrandoData.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        UsuarioSistema.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        UsuarioSistema.setForeground(new java.awt.Color(0, 0, 255));
        UsuarioSistema.setText("jLabel1");

        FuncaoUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        FuncaoUsuario.setForeground(new java.awt.Color(51, 102, 255));
        FuncaoUsuario.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cliente_IP)
                    .addComponent(IP_servidor)
                    .addComponent(UsuarioSistema)
                    .addComponent(FuncaoUsuario)
                    .addComponent(MostrandoData))
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cliente_IP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IP_servidor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsuarioSistema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FuncaoUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(MostrandoData))
        );

        jPanel1.setBounds(0, 540, 390, 160);
        jDesktopPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mc_system/gestao_igreja/imagem/1aaaa.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jLabel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jLabel1.setBounds(0, 0, 1130, 740);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("Arquivo");

        jMenuItem4.setText("Ajuda");
        jMenu1.add(jMenuItem4);

        jMenuItem11.setText("Desconectar");
        jMenuItem11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem11MousePressed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        SairButton.setText("Sair");
        SairButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SairButtonMousePressed(evt);
            }
        });
        jMenu1.add(SairButton);

        jMenuBar1.add(jMenu1);

        EBD_Menu.setText("Escola Biblica Dominical");

        jMenuItem3.setText("Janela Inicial");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem3MousePressed(evt);
            }
        });
        EBD_Menu.add(jMenuItem3);

        jMenuItem5.setText("Lançamento de Oferta");
        jMenuItem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem5MousePressed(evt);
            }
        });
        EBD_Menu.add(jMenuItem5);

        jMenuItem6.setText("Relatório de Presença");
        jMenuItem6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem6MousePressed(evt);
            }
        });
        EBD_Menu.add(jMenuItem6);

        jMenuBar1.add(EBD_Menu);

        Financeiro_Menu.setText("Financeiro");

        jMenuItem9.setText("Tesouraria");
        jMenuItem9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem9MousePressed(evt);
            }
        });
        Financeiro_Menu.add(jMenuItem9);

        jMenuItem7.setText("Fechamento de Caixa");
        jMenuItem7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem7MousePressed(evt);
            }
        });
        Financeiro_Menu.add(jMenuItem7);

        jMenuItem8.setText("Relatório de Membros Dizimistas");
        jMenuItem8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem8MousePressed(evt);
            }
        });
        Financeiro_Menu.add(jMenuItem8);

        jMenuBar1.add(Financeiro_Menu);

        Secretaria_Menu.setText("Secretaria");

        jMenuItem10.setText("Programa Principal");
        jMenuItem10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem10MousePressed(evt);
            }
        });
        Secretaria_Menu.add(jMenuItem10);

        jMenuBar1.add(Secretaria_Menu);

        Agenda_Menu.setText("Agenda");

        jMenuItem12.setText("Agenda");
        jMenuItem12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem12MousePressed(evt);
            }
        });
        Agenda_Menu.add(jMenuItem12);

        jMenuBar1.add(Agenda_Menu);

        tiMenu.setText("TI");

        jMenuItem13.setText("Criar Usuário");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        tiMenu.add(jMenuItem13);

        jMenuBar1.add(tiMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MousePressed
        // TODO add your handling code here:
        EscolaBiblicaDominical abrir = new EscolaBiblicaDominical();
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuItem3MousePressed

    private void SairButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairButtonMousePressed
        // TODO add your handling code here:
  FecharTela();  
        
    }//GEN-LAST:event_SairButtonMousePressed

    private void jMenuItem5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem5MousePressed
        // TODO add your handling code here:
        LancaOferta abrir = new LancaOferta();
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuItem5MousePressed

    private void jMenuItem6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem6MousePressed
        // TODO add your handling code here:
        Relatorio_Presenca abrir = new Relatorio_Presenca();
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuItem6MousePressed

    private void jMenuItem7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem7MousePressed
        TelaLancamentos abrir = new TelaLancamentos();
        abrir.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem7MousePressed

    private void jMenuItem8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem8MousePressed
        Dizimos abrir = new Dizimos();
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuItem8MousePressed

    private void jMenuItem9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem9MousePressed
        Principal abrir = new Principal();
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuItem9MousePressed

    private void jMenuItem10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem10MousePressed
        // TODO add your handling code here:
        Secretaria abrir = new Secretaria();
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuItem10MousePressed

    private void jMenuItem11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem11MousePressed
        // TODO add your handling code here:
        ConectaSystem abrir = new ConectaSystem();
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem11MousePressed

    private void jMenuItem12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem12MousePressed
        // TODO add your handling code here:
        Agenda abrir = new Agenda();
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuItem12MousePressed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        CriaUsuario abrir = new CriaUsuario();
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Agenda_Menu;
    private javax.swing.JLabel Cliente_IP;
    private javax.swing.JMenu EBD_Menu;
    private javax.swing.JMenu Financeiro_Menu;
    private javax.swing.JLabel FuncaoUsuario;
    private javax.swing.JLabel IP_servidor;
    private javax.swing.JLabel MostrandoData;
    private javax.swing.JMenuItem SairButton;
    private javax.swing.JMenu Secretaria_Menu;
    private javax.swing.JLabel UsuarioSistema;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu tiMenu;
    // End of variables declaration//GEN-END:variables

    private void VerificaUsuario() {
        switch (funcao) {
            case "Geral":
                break;
            case "Secretaria":
                EBD_Menu.setEnabled(false);
                Financeiro_Menu.setEnabled(false);
                tiMenu.setEnabled(false);
                break;
            case "Financeiro":
                EBD_Menu.setEnabled(false);
                Secretaria_Menu.setEnabled(false);
                Agenda_Menu.setEnabled(false);
                tiMenu.setEnabled(false);
                break;
            case "Secretaria_EBD":
                Financeiro_Menu.setEnabled(false);
                Secretaria_Menu.setEnabled(false);
                Agenda_Menu.setEnabled(false);
                tiMenu.setEnabled(false);
                break;
        }
    }

    private void MostraDataAtual() 
    {
        Date agora = new Date();
        DateFormat d1,d2;
        String f1;
        
        d1 = DateFormat.getDateInstance(DateFormat.FULL);
        d2 = new SimpleDateFormat("hh:mm");
        MostrandoData.setText(d1.format(agora));
    }

    private void MostraConexao() {
        
        try {
            Cliente_IP.setText("Cliente IP: "+InetAddress.getLocalHost().getHostAddress());
        } catch (UnknownHostException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
       IP_servidor.setText("Servidor IP: "+con.mostraIP());
    }
    
    private void FecharTela()
    {
            int confirma = 0;  
            confirma = JOptionPane.showConfirmDialog(rootPane, "DESEJA REALMENTE SAIR ?", null, confirma);
            System.out.println(confirma);
            if (confirma == 0){
                 System.exit(0);
            }
      
    }
}

